title: bitspossessed
# @TODO: This needs to be changed to the final URL before we publish the website
url: https://bitspossessed.github.io/website
description: Some description about us
markdown: kramdown
