# Global variables we want to use across the page
title: bitspossessed
# @TODO: This needs to be changed to the final URL before we publish the website
url: https://bitspossessed.github.io/website
description: Some description about us

# These are the collections of data we're rendering on our page
collections:
  - projects
  - members
  - links

# Use a different markdown renderer
markdown: kramdown

# Set `default` layout for all pages
defaults:
  - scope:
      path: ''
    values:
      layout: 'default'
